### ISSUE TITLE
On save focus shifts to Mac Preview application window

### ISSUE THREAD

**Issue by dineshdh** [chialiyun/DiagramsPreviewerVSCExt#8] opened 2023-09-20 09:03 UTC
When working in VSCode and I save changes to the python file, it updates the rendered diagram in the Diagrams Preview tab in VSCode, but then proceeds to open the previewDiagram.png and changes focus from VSCode to the mac Preview application. Makes the whole extension unusable

I noticed this only happens with the [C4 example](https://diagrams.mingrammer.com/docs/nodes/c4#c4-diagrams), not with things like the [Quick Start example](https://diagrams.mingrammer.com/docs/getting-started/installation#quick-start)

**Comment by dineshdh** [comment] 2023-09-22 10:17
previewDiagram.py seems to be missing `show=False` with C4 diagrams

Actual
```
with Diagram("Container diagram for Internet Banking System", direction="TB",  graph_attr=graph_attr,filename="previewDiagram",):
```

Expected
```
with Diagram("Container diagram for Internet Banking System", direction="TB", show=False, graph_attr=graph_attr,filename="previewDiagram",):
```

**Comment by chialiyun** [comment] 2023-09-24 14:17
Hi @dineshdh, thank you for reporting this with great details! 
We are sorry for the issue and will be working on the bug fix. 🙏

**Comment by chialiyun** [comment] 2023-09-24 15:43
Hi @dineshdh, we have fixed the issue and published a new version. Would you like to give `v1.0.7` ([link to extension](https://marketplace.visualstudio.com/items?itemName=tehpeng.diagramspreviewer)) a try? 
Feel free to reach out again if the issue is still occurring for you.

**Comment by chialiyun** [comment] 2023-10-16 12:27
Closing this since we have not hear any issues relating to this for quite sometime. 😄

**Closed as completed by chialiyun** 2023-10-16 12:27 UTC
Labels: bug
